# Configuration for Brent Oil Price Change-Point Analysis
# Project: Birhan Energies - Energy Market Intelligence

# Data Configuration
data:
  # Brent oil price data
  brent_oil:
    start_date: "1987-05-20"
    end_date: "2022-09-30"
    source: "yahoo"  # yfinance source
    symbol: "BZ=F"  # Brent crude futures
    
  # Paths
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  events_data_path: "data/events"

# Change-Point Model Configuration
change_point_model:
  model_type: "hierarchical"  # basic, robust, hierarchical, online
  max_changepoints: 25
  changepoint_prior_scale: 0.05
  changepoint_range: 0.8
  sigma_prior: 5.0
  mu_prior_scale: 10.0
  nu_prior: 4.0  # For Student-t model
  
  # MCMC Configuration
  mcmc:
    draws: 2000
    tune: 1000
    chains: 4
    cores: 4
    target_accept: 0.95
    max_treedepth: 12
  
  # Variational Inference Configuration
  variational:
    n: 50000
    method: "advi"

# Regime-Switching Model Configuration
regime_model:
  model_type: "ms_ar"  # ms_ar, ms_x, hmm, tar
  n_regimes: 3
  order: 2
  switching_variance: true
  switching_trend: true
  max_iter: 1000
  tolerance: 1e-6
  random_state: 42

# Volatility Model Configuration
volatility_model:
  model_type: "garch"  # garch, egarch, gjr_garch, stochastic_vol, regime_vol
  p: 1  # GARCH order
  q: 1  # ARCH order
  mean_model: "constant"  # constant, ar, har
  distribution: "normal"  # normal, t, skewt
  max_iter: 1000
  tolerance: 1e-6
  rescale: true

# Ensemble Model Configuration
ensemble_model:
  models:
    random_forest:
      enabled: true
      params:
        n_estimators: 100
        max_depth: 10
        random_state: 42
    gradient_boosting:
      enabled: true
      params:
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 6
        random_state: 42
    linear_regression:
      enabled: true
      params: {}
    ridge_regression:
      enabled: true
      params:
        alpha: 1.0
        random_state: 42
  
  ensemble_method: "weighted_average"  # simple_average, weighted_average, stacking
  weight_method: "performance"  # equal, performance, dynamic
  
  feature_engineering:
    lags: [1, 2, 3, 5, 10, 20]
    rolling_windows: [5, 10, 20, 30]
    technical_indicators: true
    volatility_features: true
  
  validation:
    method: "time_series_split"
    n_splits: 5
    test_size: 0.2
  
  # File formats
  price_data_file: "brent_oil_prices.csv"
  events_data_file: "geopolitical_events.csv"

# Geopolitical Events (Key events affecting oil prices)
events:
  # Major events to research and compile
  categories:
    - "OPEC_decisions"
    - "geopolitical_conflicts"
    - "economic_sanctions"
    - "supply_disruptions"
    - "financial_crises"
    - "policy_changes"
  
  # Event data structure
  required_fields:
    - "date"
    - "event_name"
    - "category"
    - "description"
    - "expected_impact"
    - "region"

# Bayesian Change Point Detection Configuration
change_point_detection:
  # PyMC model parameters
  model:
    prior_changepoint_prob: 0.01  # Prior probability of change point
    n_changepoints: 25  # Maximum number of change points
    changepoint_range: 0.8  # Proportion of history for change points
    
  # MCMC sampling parameters
  sampling:
    draws: 2000
    tune: 1000
    chains: 4
    cores: 4
    target_accept: 0.95
    
  # Model selection
  model_comparison:
    methods: ["WAIC", "LOO", "DIC"]
    
# Time Series Analysis Configuration
time_series:
  # Preprocessing
  preprocessing:
    handle_missing: "interpolate"  # Options: drop, interpolate, forward_fill
    outlier_detection: true
    outlier_threshold: 3.0  # Standard deviations
    
  # Stationarity tests
  stationarity_tests:
    - "ADF"  # Augmented Dickey-Fuller
    - "KPSS"  # Kwiatkowski-Phillips-Schmidt-Shin
    - "Phillips-Perron"
    
  # Differencing
  max_diff_order: 2

# Visualization Configuration
visualization:
  # Plot settings
  style: "plotly_white"
  color_palette: ["#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"]
  figure_size:
    width: 1200
    height: 600
  
  # Interactive dashboard
  dashboard:
    framework: "streamlit"  # Options: streamlit, dash
    port: 8501
    theme: "light"
    
  # Export settings
  export:
    format: ["png", "html", "pdf"]
    dpi: 300
    
# Model Evaluation
evaluation:
  # Metrics for change point detection
  metrics:
    - "precision"
    - "recall"
    - "f1_score"
    - "mean_absolute_error"
    
  # Cross-validation
  cv:
    method: "time_series_split"
    n_splits: 5
    test_size: 0.2

# Output Configuration
output:
  # Results directory structure
  results_dir: "results"
  subdirs:
    - "models"
    - "plots"
    - "reports"
    - "data_analysis"
    
  # Report generation
  reports:
    formats: ["html", "pdf"]
    template: "modern_report_template.html"
    
# Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name} | {message}"
  file: "logs/brent_oil_analysis.log"
  rotation: "10 MB"
  retention: "30 days"

# Performance Configuration
performance:
  # Parallel processing
  n_jobs: -1  # Use all available cores
  
  # Memory management
  chunk_size: 10000
  
  # Caching
  cache_enabled: true
  cache_dir: ".cache"

# API Configuration (for data fetching)
api:
  # Rate limiting
  rate_limit:
    requests_per_minute: 60
    
  # Retry configuration
  retry:
    max_attempts: 3
    backoff_factor: 2
    
# Environment Configuration
environment:
  development:
    debug: true
    log_level: "DEBUG"
    
  production:
    debug: false
    log_level: "INFO"
