name: Model & Data Monitoring

on:
  schedule:
    # Run every 6 hours to monitor model performance
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  data-drift-detection:
    name: Data Drift Detection
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install evidently
        
    - name: Check for data drift
      run: |
        python scripts/detect_data_drift.py
        
    - name: Generate drift report
      run: |
        python scripts/generate_drift_report.py
        
    - name: Upload drift report
      uses: actions/upload-artifact@v3
      with:
        name: data-drift-report
        path: reports/data_drift_report.html
        
    - name: Send alert if drift detected
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        channel: '#data-alerts'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        
  model-performance-monitoring:
    name: Model Performance Monitoring
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Check model performance
      env:
        MODEL_ENDPOINT: ${{ secrets.MODEL_ENDPOINT }}
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python scripts/monitor_model_performance.py
        
    - name: Generate performance report
      run: |
        python scripts/generate_performance_report.py
        
    - name: Upload performance report
      uses: actions/upload-artifact@v3
      with:
        name: model-performance-report
        path: reports/model_performance_report.html
        
  system-health-check:
    name: System Health Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Check dashboard health
      run: |
        curl -f https://brent-oil-analysis.herokuapp.com/health || exit 1
        
    - name: Check API endpoints
      run: |
        curl -f https://api.brent-oil-analysis.com/v1/health || exit 1
        
    - name: Check data pipeline status
      env:
        PIPELINE_API: ${{ secrets.PIPELINE_API }}
      run: |
        python scripts/check_pipeline_health.py
        
    - name: Send health report
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        channel: '#system-health'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
